/*
* generated by Xtext
*/
package com.ge.research.sadl.testsuite.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.ge.research.sadl.testsuite.services.TestSuiteGrammarAccess;

public class TestSuiteParser extends AbstractContentAssistParser {
	
	@Inject
	private TestSuiteGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.ge.research.sadl.testsuite.ui.contentassist.antlr.internal.InternalTestSuiteParser createParser() {
		com.ge.research.sadl.testsuite.ui.contentassist.antlr.internal.InternalTestSuiteParser result = new com.ge.research.sadl.testsuite.ui.contentassist.antlr.internal.InternalTestSuiteParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTestAccess().getGroup(), "rule__Test__Group__0");
					put(grammarAccess.getModelAccess().getTestsAssignment(), "rule__Model__TestsAssignment");
					put(grammarAccess.getTestAccess().getNameAssignment_1(), "rule__Test__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.ge.research.sadl.testsuite.ui.contentassist.antlr.internal.InternalTestSuiteParser typedParser = (com.ge.research.sadl.testsuite.ui.contentassist.antlr.internal.InternalTestSuiteParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TestSuiteGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TestSuiteGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
