/*
 * generated by Xtext 2.25.0
 */
package com.naturalsemantics.sadl.sitl.validation

import org.eclipse.xtext.validation.Check
import com.ge.research.sadl.sADL.SadlSimpleTypeReference

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class SITLValidator extends AbstractSITLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					SITLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	@Check
	override checkSadlSimpleTypeReference(SadlSimpleTypeReference ref) {
		if (ref.type.name === null) {
//			error("Undefined type", SADL_SIMPLE_TYPE_REFERENCE__TYPE, UNRESOLVED_SADL_RESOURCE)
		}
		else {
			super.checkSadlSimpleTypeReference(ref)
		}
	}
}
