# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    # Location of Dockerfile
    directory: "/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.product/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    # Location of Dockerfile
    directory: "/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/apps/browser-app/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Location of .github/workflows
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    # Location of poms
    directory: "/sadl3/com.ge.research.sadl.parent/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Yarn
  - package-ecosystem: "npm"
    # Location of package manifests
    directory: "/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/"
    schedule:
      interval: "daily"
    # Increase default limit of 5
    open-pull-requests-limit: 25
