git:
  depth: 1

branches:
  only:
    - development

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.gradle

os: linux
language: generic

jobs:
  include:
  - stage: "Java build [Maven]"
    language: java
    jdk: openjdk8
    services:
      - xvfb
    before_script: 
      - export M2_HOME=/usr/local/maven
      - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m -XX:PermSize=512m"
    script:
      - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml clean
      - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml verify

  - stage: "Theia build [yarn]"
    language: java
    jdk: openjdk8
    node_js: '10'
    before_script:
      - export M2_HOME=/usr/local/maven
      - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m -XX:PermSize=512m"
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
      - export PATH=$HOME/.yarn/bin:$PATH
      - nvm install 10.15.3
      - nvm use 10.15.3
    script:
      - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml clean
      - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml -Dmaven.test.skip=true verify
      - yarn --cwd ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension
    before_deploy:
      - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
    deploy:
      provider: script
      script: yarn --cwd ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension run publish:next
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(development)$
      skip_cleanup: true

  - stage: "Publish [docker]"
    language: generic
    services:
      - docker
    before_script: 
      - sudo apt-get update
      - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      - sudo apt-get -y install jq
      - npm install --global node-gyp@6.0.1
      - npm config set node_gyp "`npm prefix -g`/lib/node_modules/node-gyp/bin/node-gyp.js"
      - echo "npm config get node_gyp -> `npm config get node_gyp`"
    script:
      - cp -rf sadl3/com.ge.research.sadl.parent/theia-sadl-extension/yarn.lock sadl3/com.ge.research.sadl.parent/theia-sadl-extension/browser-app/yarn.lock # Reuse the yarn.lock file.
      - NEXT_VERSION=`npm view sadl-extension@next version` # Get the next version that we want to include in the image.
      - cd ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension/browser-app # Here is the Dockerfile
      - mv -f ./package.json ./package.json.original # Rename the package.json. We want to update the version and used the updated one for Docker.
      - cat ./package.json.original | jq .version=\"$NEXT_VERSION\" > package.json # Update the version to use the most recent `next`.
      - travis_wait docker build --build-arg "GITHUB_TOKEN=$GITHUB_TOKEN" --no-cache . -t theiaide/sadl:$NEXT_VERSION  # Build the Docker image.
      - docker tag theiaide/sadl:$NEXT_VERSION theiaide/sadl:next # Tag the Docker image.
    before_deploy:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    deploy:
      provider: script
      script: docker push theiaide/sadl
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(development)$
      skip_cleanup: true
