language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - development

cache:
  directories:
  - $HOME/.m2/repository

env:
   global:
    - DISPLAY=:99.0

before_install: 
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m -XX:PermSize=512m"
  - sh -e /etc/init.d/xvfb start - sleep 10 

script:
  - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml clean verify