shallow_clone: true

branches:
  only:
  - development

platform:
  - x64

build_script:
  - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml clean
  - mvn -f ./sadl3/com.ge.research.sadl.parent/pom.xml verify -U

cache:
 - C:\Users\appveyor\.m2
