/*
 * generated by Xtext 2.11.0.RC2
 */
package com.ge.research.sadl.testsuite.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TestSuiteScopeProvider extends AbstractTestSuiteScopeProvider {

}
