/**
 * generated by Xtext
 */
package com.ge.research.sadl.validation;

import com.ge.research.sadl.validation.AbstractMappingValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MappingValidator extends AbstractMappingValidator {
}
