/*
* generated by Xtext
*/
package com.ge.research.sadl.testsuite;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TestSuiteUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.ge.research.sadl.testsuite.ui.internal.TestSuiteActivator.getInstance().getInjector("com.ge.research.sadl.testsuite.TestSuite");
	}
	
}
