/*
 * generated by Xtext
 */
package com.ge.research.sadl.testsuite.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestSuiteUiModule extends com.ge.research.sadl.testsuite.ui.AbstractTestSuiteUiModule {
	public TestSuiteUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
