/*
 * generated by Xtext
 */
package com.ge.research.sadl.testsuite;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestSuiteRuntimeModule extends com.ge.research.sadl.testsuite.AbstractTestSuiteRuntimeModule {

}
