/*
* generated by Xtext
*/
package com.ge.research.sadl.testsuite;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestSuiteStandaloneSetup extends TestSuiteStandaloneSetupGenerated{

	public static void doSetup() {
		new TestSuiteStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

