/**
 * generated by Xtext
 */
package com.ge.research.sadl.testsuite.validation;

import com.ge.research.sadl.testsuite.validation.AbstractTestSuiteValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TestSuiteValidator extends AbstractTestSuiteValidator {
}
