/*
 * generated by Xtext 2.11.0.RC2
 */
package com.ge.research.sadl.importer.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class TemplateOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
