/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package com.ge.research.sadl.validation

import com.ge.research.sadl.model.DeclarationExtensions
import com.ge.research.sadl.sADL.SADLPackage
import com.ge.research.sadl.sADL.SadlModel
import com.google.inject.Inject
import org.eclipse.xtext.validation.Check
import com.ge.research.sadl.utils.SadlUtils
import com.ge.research.sadl.sADL.RuleStatement
import org.eclipse.xtext.nodemodel.util.NodeModelUtils
import org.eclipse.xtext.EcoreUtil2
import com.ge.research.sadl.sADL.Name
import java.util.ArrayList

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class SADLValidator extends AbstractSADLValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Inject DeclarationExtensions declarationExtensions;

	public static String INVALID_MODEL_URI = "INVALID_MODEL_URI"
	public static String INVALID_IMPORT_URI = "INVALID_IMPORT_URI"
	public static String INVALID_MODEL_ALIAS = "INVALID_MODEL_ALIAS"
	public static String INVALID_MODEL_FILENAME = "INVALID_MODEL_FILENAME"
	public static String UNBOUND_VARIABLE_IN_RULE_HEAD = "UNBOUND_VARIABLE_IN_RULE_HEAD"
	
	@Check
	def checkSadlModel(SadlModel model) {
		var thisUri = model.baseUri
		var errMsg = SadlUtils.validateUri(thisUri);
		if (errMsg != null) {
			error(errMsg, SADLPackage.Literals.SADL_MODEL__BASE_URI, INVALID_MODEL_URI);
		}
		var thisRsrc = model.eResource
		var thisURL = thisRsrc.URI;
		var thisFN = thisURL.lastSegment
		var rsrcItr = thisRsrc.resourceSet.resources.iterator
		while (rsrcItr.hasNext()) {
			var otherRsrc = rsrcItr.next
			if (!otherRsrc.equals(thisRsrc)) {
				// this isn't the same resource
				var otherModel = otherRsrc.contents.get(0) as SadlModel
				var otherRsrcUri = otherModel.baseUri
				var otherURL = otherRsrc.URI
				var otherFN = otherURL.lastSegment
				if (thisFN.equals(otherFN)) {
					error("The filename (" + thisFN + ") is already used by model '" + otherURL + "'; filenames must be unique within a project.", SADLPackage.Literals.SADL_MODEL__BASE_URI, INVALID_MODEL_FILENAME)
				}
				if (thisUri != null && thisUri.equals(otherRsrcUri)) {
					error("This URI is already used by model '" + otherFN + "'", SADLPackage.Literals.SADL_MODEL__BASE_URI, INVALID_MODEL_URI)
				}
				var thisAlias = model.alias
				var otherAlias = otherModel.alias
				if (otherAlias != null && thisAlias != null && otherAlias.equals(thisAlias)) {
					error("This alias is already used by model '" + otherFN + "'; must be unique", SADLPackage.Literals.SADL_MODEL__ALIAS, INVALID_MODEL_ALIAS)
				}
			}
		}
		var imports = model.imports
		// does an import need any validation?
		if (imports != null) {
			var itr = imports.iterator
			while (itr.hasNext) {
				var imp = itr.next;
				var sm = imp.importedResource
				if (sm != null) {
					var impuri = sm.baseUri
					if (impuri == null) {
						errMsg = "Model '" + thisUri + "' has an import which appears to be null";
					}
					else if (impuri.equals(thisUri)) {
						error("A model cannot import itself", SADLPackage.Literals.SADL_IMPORT__IMPORTED_RESOURCE)
					}
					else {
						errMsg = SadlUtils.validateUri(impuri);
						if (errMsg != null) {
							error(errMsg, SADLPackage.Literals.SADL_IMPORT__IMPORTED_RESOURCE);
						}
					}
				}
			}
		}
	}
	
	@Check
	def checkRuleStatement(RuleStatement rule) {
		// make sure all variables used in the head are bound in the bod
		val itr = EcoreUtil2.getAllContents(rule.thens).filter(Name).toList.iterator
		while (itr.hasNext) {
			var name = itr.next
			if (name.name.equals(name)) {
				var errMsg = "Rule conclusion contains variable '" + declarationExtensions.getConcreteName(name) + " which is not bound in the rule premises."
				error(errMsg, SADLPackage.Literals.RULE_STATEMENT__THENS, UNBOUND_VARIABLE_IN_RULE_HEAD);
			}
		}
	}
}
