/************************************************************************
 * Copyright © 2007-2017 - General Electric Company, All Rights Reserved
 * 
 * Project: SADL
 * 
 * Description: The Semantic Application Design Language (SADL) is a
 * language for building semantic models and expressing rules that
 * capture additional domain knowledge. The SADL-IDE (integrated
 * development environment) is a set of Eclipse plug-ins that
 * support the editing and testing of semantic models using the
 * SADL language.
 * 
 * This software is distributed "AS-IS" without ANY WARRANTIES
 * and licensed under the Eclipse Public License - v 1.0
 * which is available at http://www.eclipse.org/org/documents/epl-v10.php
 * 
 ***********************************************************************/
package com.ge.research.sadl.ui.tests;

import static com.ge.research.sadl.utils.ResourceManager.OWLDIR;
import static com.ge.research.sadl.utils.ResourceManager.OWLFILEEXTWITHPREFIX;

import java.nio.file.Paths;

import com.ge.research.sadl.ui.tests.AbstractSadlPlatformTest.GeneratedOutputLocationProvider;

/**
 * Enumeration of the supported output formats that are generated by the
 * application.
 * 
 * @author akos.kitta
 */
public enum GeneratedOutputFormat implements GeneratedOutputLocationProvider {

	/**
	 * The OWL format.
	 */
	OWL {

		@Override
		public String get(String inputFilePath) {
			return OWLDIR + "/" + extractFileName(inputFilePath) + OWLFILEEXTWITHPREFIX;
		}

	},

	/**
	 * The rules output.
	 */
	RULES {

		@Override
		public String get(String inputFilePath) {
			return OWLDIR + "/" + extractFileName(inputFilePath) + ".rules";
		}

	};

	protected String extractFileName(String inputFilePath) {
		return Paths.get(inputFilePath).getFileName().toString().replaceFirst("[.][^.]+$", "");
	}

}
