/*
 * generated by Xtext 2.11.0.RC2
 */
package com.ge.research.sadl.testsuite.validation

import com.ge.research.sadl.sADL.SadlModel
import com.ge.research.sadl.testsuite.testSuite.TestSuitePackage
import org.eclipse.xtext.validation.Check
import com.ge.research.sadl.testsuite.testSuite.Test
import com.ge.research.sadl.testsuite.testSuite.TestModel

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TestSuiteValidator extends AbstractTestSuiteValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					TestSuitePackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkSadlModel(TestModel model) {
		if (model.eContainer instanceof Test) {
			val tst = model.eContainer as Test
			val root = tst.eContainer as SadlModel
			var boolean found = false;
			for (t : root.elements) {
				if (t.equals(model)) {
					if (found) {
						warning("Duplicate test", model, TestSuitePackage.Literals.TEST__TEST_RESOURCE)
					}
				}
			}
		}
	}
	
}
