/*
 * generated by Xtext 2.11.0.RC2
 */
package com.ge.research.sadl.testsuite.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TestSuiteProposalProvider extends AbstractTestSuiteProposalProvider {
}
