# Runs after every pull request or push (except tag-only pushes)

name: SADL Continuous Integration Workflow
on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

jobs:

# Test job:
#  - Builds SADL source
#  - Runs unit tests

  test:
    strategy:
      matrix:
        distribution: [ adopt ]
        java-version: [ 11 ]
        os: [ macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out SADL source
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Build SADL source
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B package --file sadl3/com.ge.research.sadl.parent/pom.xml

# Build job:
#  - Builds SADL source
#  - Runs unit tests
#  - Uploads SADL update repository
#  - Builds WebSADL extension
#  - Publishes WebSADL npm package
#  - Builds WebSADL Docker image
#  - Pushes Docker image to Docker Hub

  build:
    strategy:
      matrix:
        distribution: [ adopt ]
        java-version: [ 11 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out SADL source
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Build SADL source
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B package --file sadl3/com.ge.research.sadl.parent/pom.xml

    - name: Get SADL zip filename
      run: |
        cd sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.update/target
        echo "sadlzip=$(echo com.ge.research.sadl.update*.zip | sed 's/.zip//')" >> $GITHUB_ENV

    - name: Upload SADL update repository
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.sadlzip }}
        path: sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.update/target/repository

    - name: Set up Node.js 10.x
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 10.15.3
        registry-url: https://registry.npmjs.org

    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Build WebSADL extension
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn --cwd ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension

    - name: Publish WebSADL npm package
      if: github.ref == 'refs/heads/development'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        yarn --cwd sadl3/com.ge.research.sadl.parent/theia-sadl-extension run publish:next

    - name: Build WebSADL Docker image
      if: github.ref == 'refs/heads/development'
      run: |
        npm install --global node-gyp@6.0.1
        npm config set node_gyp "`npm prefix -g`/lib/node_modules/node-gyp/bin/node-gyp.js"
        echo "npm config get node_gyp -> `npm config get node_gyp`"
        sadl3/com.ge.research.sadl.parent/theia-sadl-extension/scripts/build-docker.sh

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/development'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push WebSADL image to Docker Hub
      if: github.ref == 'refs/heads/development'
      run: docker push theiaide/sadl:next
